machines = {
    'megapunch': 'TM Vendor in Fuchsia City for $6,000',
    'razorwind': 'TM Vendor in Fuchsia City for $3,500',
    'whirlwind': 'TM Vender in Fuchsia City for $4,000',
    'megakick': 'TM Vendor in Fuchsia City for $6,000 / FOUND on Route 4',
    'toxic': 'FOUND in Fiery Path (hidden inside a Rock) / Fuchsia City Gym - $5,000',
    'bodyslam': 'TM Vendor in Fuchsia City for $6,500',
    'takedown': 'FOUND in Mt. Moon 1F / TM Vendor in Fuchsia City for $6,500',
    'bubblebeam': 'TM Vendor in Fuchsia City for $3,000',
    'watergun': 'FOUND in Mt. Moon B1F',
    'icebeam': 'all Department Stores for $9,000 / FOUND at Seafoam B2F / FOUND at Route 216 / FOUND at Abandoned Ship B1F Room 4 / possible Held Item of Spheal on Route 105',
    'blizzard': 'Snowpoint City Gym for $7,000 / Lorelei Boss Battle Reward / Held item of Frillish on Route 105',
    'hyperbeam': 'all Department Stores for $15,000',
    'payday': 'TM Vendor in Fuchsia City for $1,500',
    'submission': 'TM Vendor in Fuchsia City for $6,500 / FOUND in Route 15',
    'seismictoss': 'FOUND in Route 25 / FOUND aboard the SS Anne',
    'megadrain': 'TM Vendor in Fuchsia City for $3,000',
    'solarbeam': 'all Department Stores for $15,000 / possible Reward from Erika Boss',
    'dragonrage': 'FOUND in the Viridian Maze /TM Vendor in Fuchsia City for $2,000',
    'thunderbolt': 'all Department Stores for $9,000 / possible Reward from Lt. Surge Boss / FOUND in Cerulean Cave 2F / possible Reward from Pokestop next to Power Plant',
    'thunder': 'Power Plant for $12,000',
    'earthquake': 'Viridian City Gym - $9,000 / possible Reward from Bruno Boss / Historical Site (Artifact Maniac Hastor) - 75 Artifact Points',
    'fissure': 'TM Vendor in Fuchsia City for $15,000 / possible Celadon Task Master Reward',
    'dig': 'all Department Stores for $3,500 / Route 36 (Smuggler) - $5,000 / Historical Site (Artifact Maniac Hastor) - 50 Artifact Points / FREE Cerulean House 6 / FREE Route 114',
    'psychic': 'Saffron City Gym for $9,000',
    'teleport': 'Eumi Island Theme Park 1 - $5,000',
    'doubleteam': 'Eumi Island Theme Park 1 - $8,000',
    'reflect': 'all Department Stores for $4,000',
    'bide': 'TM Vendor in Fuchsia CIty for $1,000',
    'selfdestruct': 'Eumi Island Theme Park 1 - $8,000',
    'eggbomb': 'TM Vendor in Fuchsia City for $6,500',
    'fireblast': 'Cinnabar City Gym for $12,000',
    'swift': 'TM Vendor in Fuchsia City for $3,000',
    'skullbash': 'TM Vendor in Fuchsia City for $6,000',
    'softboiled': 'TM Vendor in Fuchsia City for $5,000',
    'dreameater': 'Celadon City Department Store for $6,000 / possible Celadon Task Master Reward',
    'rest': 'all Department Stores for $8,000 / Vermilion City - $6,000 - Special Offer: 5 for $24,000',
    'thunderwave': 'all Department Stores',
    'psywave': 'TM Vendor in Fuchsia City for $3,000 / FOUND in Goldenrod Underground Path / FOUND in Granite Cave B1F',
    'rockslide': 'Celadon Department Store for $8,000 / Goldenrod Mart 3 - $3,000 / Historical Site (Artifact Maniac Hastor) - 50 Artifact Pieces',
    'endure': 'Eumi Island Theme Park 1 - $5,000',
    'dragonclaw': 'Celadon Department Store and Goldenrod Department Store for $7,000 / possible Reward from Shary & Shaui Boss',
    'psyshock': 'Goldenrod Department Store for $9,000 / Historical Site (Artifact Maniac Hastor) - 75 Artifact Pieces',
    'calmmind': 'Trainers Valley - $6,000 / Mossdeep City Gym - $6,000 / possible Reward from Shary & Shaui Boss',
    'roar': 'Celadon Mart 3 - $4,000 / Route 114 (Katy Perry) - $2,000 - Special Offer: 5 for $8,000 / FOUND on Route 213 (Rock Climb / Abseil Rope needed)',
    'hail': 'Lilycove Department Store for $4,500',
    'bulkup': 'Dewford Town Gym for $3,000',
    'echoedvoice': 'Goldenrod City Gym for $3,500',
    'hiddenpower': 'Veilstone Department Store for $6,500 / possible Reward from Lt. Surge Boss',
    'sunnyday': 'Lilycove Department Store for $4,500',
    'taunt': 'Goldenrod Department Store and Veilstone Department Store for $6,000 / possible Prize from Trick House Challenge (Route 110) / possible Reward from Shary & Shaui Boss / FOUND in Goldenrod Underground Basement (during Radio Station Quest)',
    'dynamicpunch': ' Cianwood City Gym for $12,000',
    'drainpunch': 'Veilstone City Gym for $8,000',
    'dragonbreath': 'Goldenrod Department Store for $3,500',
    'lightscreen': 'all Department Stores for $4,000',
    'protect': 'Trainers Valley - $5,500 / all Department Stores for $6,000',
    'raindance': 'Lilycove Department Store for $4,500',
    'roost': 'Fortree City Gym for $9,000 / Historical Site (Artifact Maniac Hastor) - 75 Artifact Pieces',
    'dragonpulse': 'Blackthorn City Gym for $8,500',
    'swordsdance': 'Trainers Valley - $10,000 / Celadon Mart 6 in exchange for a Soda Pop (one time only) / Historical Site (Artifact Maniac Hastor) - 100 Artifact Pieces',
    'curse': 'Eumi Island Theme Park 1 - $5,000 / Hearthome City House 1 - $15,000 - Special Offer: 5 for $60,000',
    'shadowball': 'Hearthome City Gym for $9,000 / possible Celadon Task Master Reward / FOUND in Hall of Fame (Lavender Town) / possible Reward from Morty Boss / possible Reward from Shary & Shaui Boss',
    'brickbreak': 'Lilycove Department Store for $6,500',
    'flamethrower': 'all Department Stores for $9,000 / possible Reward from Shary & Shaui Boss',
    'sludgebomb': 'Dewford Town - $5,000 - Special Offer: 5 for $20,000 (needs 5 Hoenn badges)',
    'sandstorm': 'Lilycove Department Store for $4,500 / FOUND in Route 111 Desert',
    'rocktomb': 'Rustboro City Gym - $3,000 - Special Offer: 5 for $12,000',
    'auroraveil': 'Snowpoint City House - $15,000 - Special Offer: 5 for $60,000',
    'facade': 'Petalburg City Gym - $6,000 / possible Reward from Shary & Shaui Boss',
    'thief': 'Celadon Mart 6 - $7,500 (after finishing Thief Quest) / possible Reward from Shary & Shaui Boss / FREE from Officer Jenny in Viridian',
    'overheat': 'Lavaridge Town Gym - $15,000',
    'headbutt': 'all Department Stores for $4,500',
    'falseswipe': 'FREE from Max in Mart Rustboro City / Route 48 - $4,000 - Special Offer: 5 for $16,000 / all Department Stores for $4,000 / possible Reward from Celadon Task Master',
    'scald': ' Sootopolis City Gym for $9,000 / possible Reward from Misty Boss',
    'willowisp': 'Veilstone Department Store for $7,000',
    'rocksmash': 'all Department Stores for $3,500 / Route 36 (Smuggler) - $5,000 / Mauville City House 2 (Nerd Julian) - $5,000 / Oreburgh City House 2 (Miner Daen) - $5,000 / Veilstone Department Store 2F - $3,500 / Ravaged Path (Explorer Tony) - $5,000 / given by Oaks Aide inside Route 11 Stop House 1F after obtaining 30 caught Pokemon',
    'shadowclaw': 'Ecruteak City Gym for $7,000 / possible Celadon Task Master Reward / FOUND in Burned Tower Floor 2 / FOUND in Granite Cave B2F / possible Reward from Shary & Shaui Boss',
    'voltswitch': 'Trainers Valley for $6,000',
    'return': 'Goldenrod Department Store and Veilstone Department Store for $8,000',
    'sleeptalk': 'all Department Stores for $7,000',
    'uturn': 'Azalea Town Gym - $6,000 / possible Reward from Bugsy Boss',
    'wildcharge': 'Sunyshore City Gym for $12,000',
    'poweruppunch': 'Eumi Island Theme Park 1 for $7,000',
    'energyball': 'Love Island House 3 for $9,000',
    'focusblast': 'Veilstone City Deparment Store and Celadon City Department Store for $12,000',
    'chargebeam': 'Vermilion City Gym for $5,000',
    'gigaimpact': 'all Department Stores for $15,000',
    'smackdown': 'Pewter City Gym for $2,000',
    'avalanche': 'Mahagony Town Gym for $12,000',
    'aerialace': 'Violet City Gym for $3,000',
    'irontail': 'Olivine City Gym for $8,000',
    'rockpolish': 'Oreburgh City Gym for $4,000',
    'grassknot': 'Eterna City Gym for $7,000',
    'flashcannon': 'Canalave City Gym for $9,000',
    'steelwing': 'Celadon City Game Corner for $7,000',
    'sludgewave': 'Celadon City Game Corner for $10,000',
    'substitute': 'Trainers Valley for $9,000',
    'waterpulse': 'Cerulean City Gym for $3,500',
    'gigadrain': 'Celadon City Gym for $8,000',
    'shockwave': 'Mauville City Gym for $3.500',
    'furycutter': 'Goldenrod City Department Store for $3,500',
    'brine': 'Pastoria City Gym for $4,000',
    'stoneedge': '$12,000 each at Mt. Silver Lower Mountainside.',
    'cut': 'FOUND aboard SS Anne (from the Captain after curing him)',
    'fly': 'Received after completing the Subway Managers Quest (not usable outside battle)',
    'surf': 'FOUND in Safari House 4 in (Kanto) Safari Area 3',
    'flash': "Given by Oak's Aide inside Route 2 Stop 3 after obtaining 10 caught Pokemon",
    'dive': 'Received from Steven at Mossdeep City Space Center 1F (after beating Mossdeep Gym)',
    'waterfall': 'FOUND at Cave of Origin B3F / FOUND at Sinnoh Safari Area Zone 4 (only if you had not found it previously)'
}